CREATE TABLE USERS (
  ID INTEGER PRIMARY KEY,
  NAME VARCHAR(30),
  EMAIL VARCHAR(30)
);

CREATE TABLE CHANNELS (
  ID INTEGER PRIMARY KEY,
  FRIENDLY_NAME VARCHAR(30) UNIQUE,
  TYPE CHAR(6),
  NAME VARCHAR(30) UNIQUE
);